### ISSUE TITLE
Multiple Kamilia phase 2 sub-phases triggered at the same time

### ISSUE THREAD

**Issue by BtbN** [Remag/DeadSplit#1]
Not sure how this might happen, but it happens:
https://clips.twitch.tv/PlumpColdbloodedSparrowAMPEnergyCherry

It messes with the numbers and clear percentages for the phases.

**Comment by Remag** [comment]
Older version maybe? Issue was supposedly fixed at some point after release.

**Comment by BtbN** [comment]
Yeah, he indeed must have been using something ancient. Readme said version 0.0.0.
Re-Downloading and auto-updating to 1.1 now, seems like it's fixed.

What's the official download source for 1.1 btw.? Just get 1.02 from delicious-fruit and auto-update it?

**Comment by Remag** [comment]
Download 1.02 and auto update, yes. Delicious fruit doesn't offer a quick and automatic way to update the link, unfortunately.
